### ISSUE TITLE
Documentation sections missing at module intialization

### ISSUE THREAD

**Issue by santaclauze** [yeutech-lab/documentation#11]
When initializing a module with styleguide, the `styleguide.ext.json` has two sections that are absent from the generated module. It creates an error during documentation build.

Remove: 
```
    {
      "name": "JSdoc",
      "description": "This part is generated from the JSdoc annotations in the source code.",
      "content": "docs/js/jsdoc.md"
    },
    {
      "name": "Changelog",
      "content": "CHANGELOG.md"
    },
```

to fix, or add the .md files at module intialization.

**Comment by kopax** [comment]
Wrong repo, see rollup-umd
